### ISSUE TITLE
GUI not working

### ISSUE THREAD

**Issue by Roger-Gu** [georgegach/flowiz#11]
Trying to use to tool on windows.
Works fine with bash command and python, yet reports this error upon trying to run the GUI:

`$ python -m flowiz.gui
> GUI webpath: C:\Users\guyixing\flowiz\flowiz\gui\web
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\guyixing\flowiz\flowiz\gui\__main__.py", line 73, in <module>
    'chromeFlags': ['--disable-http-cache']})
  File "C:\Users\guyixing\AppData\Roaming\Python\Python37\site-packages\eel\__init__.py", line 142, in start
    raise RuntimeError(api_error_message)
RuntimeError:
----------------------------------------------------------------------------------
  'options' argument deprecated in v1.0.0, see https://github.com/ChrisKnott/Eel
  To suppress this error, add 'suppress_error=True' to start() call.
  This option will be removed in future versions
----------------------------------------------------------------------------------`

Any idea how to solve this? (I have eel installed by pip)

**Comment by Roger-Gu** [comment]
Same as issue#8
